Update README.md
geekymeeky/chitchat pull request #12
Opened 2021-07-11 07:34 UTC by Prakash-Haldar

2021-07-11 17:42 UTC, geekymeeky requested changes

2021-07-11 17:42 UTC, geekymeeky commented on README.md
> +git clone --depth 1 https://github.com/<your_user_name>/chitchat.git
Make use of this. It becomes more readable and accessible as a result.
```bash
git clone https://github.com/<your_user_name>/chitchat.git
```

2021-07-11 17:42 UTC, geekymeeky commented on README.md
> +<img src="./readme_assets/CloneRepo.png" width="500">
This image isn't rendering.

2021-07-11 17:42 UTC, geekymeeky commented on README.md
> +<img src="./readme_assets/compare_pr.png" width=600>
This image isn't rendering.

2021-07-11 17:42 UTC, geekymeeky commented on README.md
> +<img src="./readme_assets/CreatePR.png" width=600>
This image isn't rendering.

2021-07-12 10:08 UTC, Prakash-Haldar commented
@geekymeeky I Have done all the Changes . Now it works Good . Please See to it

2021-07-12 12:32 UTC, geekymeeky approved these changes

2021-07-12 12:32 UTC, merged

2021-07-12 15:36 UTC, Prakash-Haldar commented
Please Send the google form of DevIncept @geekymeeky

2021-07-12 17:42 UTC, geekymeeky commented
> Please Send the google form of DevIncept @geekymeeky

@Prakash-Haldar Check the Slack channel

2021-07-12 17:42 UTC, geekymeeky commented
Fixes #12

2021-07-12 17:49 UTC, Prakash-Haldar commented
Please Send Me the Link Of Slack Channel