Add Contributing.md file
geekymeeky/chitchat pull request #19
Opened 2021-07-13 11:25 UTC by Manidipaaa

Added a Contributing.md file and fixed the grammatical errors. Removed the contents of the readme file.

2021-07-13 11:49 UTC, geekymeeky requested changes

2021-07-13 11:49 UTC, geekymeeky commented on CONTRIBUTING.md
> +
Remove these lines

2021-07-13 11:49 UTC, geekymeeky commented on CONTRIBUTING.md
> +samples, guidance on mobile development, and a full API reference.
Remove these lines

2021-07-13 11:52 UTC, geekymeeky requested changes

2021-07-13 11:52 UTC, geekymeeky commented on README.md
> -</a>
Do not delete these lines.

2021-07-13 13:27 UTC, Manidipaaa commented
Updated CONTRIBUTING.md

2021-07-13 13:51 UTC, geekymeeky requested changes
Changes that must be addressed:
- Remove `Contributors` section from `CONTRIBUTING.md`
- Contributors section should be in the Readme file. So, don't delete those markup.

2021-07-13 13:51 UTC, geekymeeky commented on CONTRIBUTING.md
> +</a>
Remove these lines

2021-07-13 13:51 UTC, geekymeeky commented on README.md
> -</a>
Do not delete these lines

2021-07-24 18:23 UTC, geekymeeky commented
@Manidipaaa any update?

2021-07-25 03:36 UTC, closed without merging