Added Chat Screen
geekymeeky/chitchat pull request #31
Opened 2021-07-18 04:14 UTC by madihamallick

**Fixes: #23**

2021-07-18 10:09 UTC, geekymeeky requested changes

2021-07-18 10:09 UTC, geekymeeky commented on lib/screens/chat_screen.dart
> +        body: SafeArea(
When using an AppBar, the SafeArea widget is not necessary. Please take it down.

2021-07-18 10:09 UTC, geekymeeky commented on lib/screens/chat_screen.dart
> +                    child: Align(
Use `mainAxisAlignment` and `crossAxisAlignment` property to align widgets under `Row` widget

2021-07-18 10:09 UTC, geekymeeky commented on lib/screens/chat_screen.dart
> +                      ),
Because we need to write text in this section, please use `TextField` widget rather than `TextButton`.

2021-07-18 10:09 UTC, geekymeeky commented on lib/screens/chat_screen.dart
> +                ]))
Use `mainAxisAlignment` and `crossAxisAlignment` property to align widgets under `Row` widget

2021-07-18 18:31 UTC, madihamallick commented
@geekymeeky Made the changes

2021-07-21 15:52 UTC, geekymeeky approved these changes
Looks great.

2021-07-21 15:53 UTC, merged